version: '3'
services:
  gobarber:
    build: .
    depends_on:
      - postgresgobarber
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - '5000:5000'
    command: yarn dev
    volumes:
      - .:/usr/src/
      - ./node_modules:/usr/src/node_modules
    links:
      - postgresgobarber
    networks:
      - gobarberbackend

  postgresgobarber:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    volumes:
      - ./src/database:/var/lib/postgresql/data
    networks:
      - gobarberbackend

networks:
  gobarberbackend:
    driver: bridge
