export const DEPARTMENTS = [
  { codigo: 17, descripcion: 'ALTO PARAGUAY' },
  { codigo: 11, descripcion: 'ALTO PARANA' },
  { codigo: 14, descripcion: 'AMAMBAY' },
  { codigo: 16, descripcion: 'BOQUERON' },
  { codigo: 6, descripcion: 'CAAGUAZU' },
  { codigo: 7, descripcion: 'CAAZAPA' },
  { codigo: 18, descripcion: 'CANINDEYU' },
  { codigo: 1, descripcion: 'CAPITAL' },
  { codigo: 12, descripcion: 'CENTRAL' },
  { codigo: 2, descripcion: 'CONCEPCION' },
  { codigo: 4, descripcion: 'CORDILLERA' },
  { codigo: 5, descripcion: 'GUAIRA' },
  { codigo: 8, descripcion: 'ITAPUA' },
  { codigo: 9, descripcion: 'MISIONES' },
  { codigo: 13, descripcion: 'NEEMBUCU' },
  { codigo: 10, descripcion: 'PARAGUARI' },
  { codigo: 15, descripcion: 'PTE. HAYES' },
  { codigo: 3, descripcion: 'SAN PEDRO' },
]
