export const DISTRICTS = [
  { codigo: 1, descripcion: 'ASUNCION (DISTRITO)', departamento: 1 },
  { codigo: 2, descripcion: 'CONCEPCION (MUNICIPIO)', departamento: 2 },
  { codigo: 3, descripcion: 'SAN LAZARO', departamento: 2 },
  { codigo: 4, descripcion: 'SAN CARLOS', departamento: 2 },
  { codigo: 5, descripcion: 'BELEN', departamento: 2 },
  { codigo: 6, descripcion: 'LORETO', departamento: 2 },
  { codigo: 7, descripcion: 'HORQUETA', departamento: 2 },
  { codigo: 8, descripcion: 'SAN SALVADOR', departamento: 2 },
  { codigo: 9, descripcion: "YBY YA'U", departamento: 2 },
  { codigo: 267, descripcion: 'SAN CARLOS DEL APA', departamento: 2 },
  { codigo: 270, descripcion: 'SARGENTO JOSE FELIX LOPEZ', departamento: 2 },
  { codigo: 280, descripcion: 'PASO BARRETO (MUNICIPIO)', departamento: 2 },
  { codigo: 281, descripcion: 'SAN ALFREDO (MUNICIPIO)', departamento: 2 },
  { codigo: 282, descripcion: 'AZOTE¿Y (MUNICIPIO)', departamento: 2 },
  { codigo: 286, descripcion: 'ARROYITO', departamento: 2 },
  { codigo: 10, descripcion: 'SAN PEDRO DE YCUAMANDYYU', departamento: 3 },
  { codigo: 11, descripcion: 'ANTEQUERA', departamento: 3 },
  { codigo: 12, descripcion: 'GRAL. E.AQUINO', departamento: 3 },
  { codigo: 13, descripcion: 'ITACURUBI DEL ROSARIO', departamento: 3 },
  { codigo: 14, descripcion: 'SAN ESTANISLAO (SANTANI)', departamento: 3 },
  { codigo: 15, descripcion: 'LIMA', departamento: 3 },
  { codigo: 16, descripcion: 'NUEVA GERMANIA', departamento: 3 },
  { codigo: 17, descripcion: 'TACUATI', departamento: 3 },
  { codigo: 18, descripcion: 'UNION', departamento: 3 },
  { codigo: 19, descripcion: '25 DE DICIEMBRE', departamento: 3 },
  { codigo: 20, descripcion: 'VILLA DEL ROSARIO', departamento: 3 },
  { codigo: 21, descripcion: 'YATAITY DEL NORTE', departamento: 3 },
  { codigo: 22, descripcion: 'ISIDORO RESQUIN', departamento: 3 },
  { codigo: 23, descripcion: 'CHORE', departamento: 3 },
  { codigo: 24, descripcion: 'SAN PABLO', departamento: 3 },
  { codigo: 25, descripcion: 'SAN JOSE DEL ROSARIO', departamento: 3 },
  { codigo: 220, descripcion: 'GUAYAIBI', departamento: 3 },
  { codigo: 226, descripcion: 'CAPIIBARY', departamento: 3 },
  { codigo: 245, descripcion: 'YRYBUCUA', departamento: 3 },
  { codigo: 263, descripcion: 'SANTA ROSA DEL AGUARAY', departamento: 3 },
  { codigo: 268, descripcion: 'LIBERACIÓN', departamento: 3 },
  { codigo: 285, descripcion: 'SAN VICENTE PANCHOLO', departamento: 3 },
  { codigo: 26, descripcion: 'CAACUPE', departamento: 4 },
  { codigo: 27, descripcion: 'ALTOS', departamento: 4 },
  { codigo: 28, descripcion: 'ARROYOS Y ESTEROS', departamento: 4 },
  { codigo: 29, descripcion: 'ATYRA', departamento: 4 },
  { codigo: 30, descripcion: 'CARAGUATAY', departamento: 4 },
  { codigo: 31, descripcion: 'EMBOSCADA', departamento: 4 },
  { codigo: 32, descripcion: 'EUSEBIO AYALA', departamento: 4 },
  { codigo: 33, descripcion: 'ISLA PUCU', departamento: 4 },
  { codigo: 34, descripcion: 'ITACURUBI DE LA CORDILLERA', departamento: 4 },
  { codigo: 35, descripcion: 'JUAN DE MENA', departamento: 4 },
  { codigo: 36, descripcion: 'NUEVA COLOMBIA', departamento: 4 },
  { codigo: 37, descripcion: 'PIRIBEBUY', departamento: 4 },
  { codigo: 38, descripcion: '1RO.DE MARZO', departamento: 4 },
  { codigo: 39, descripcion: 'SAN BERNARDINO', departamento: 4 },
  { codigo: 40, descripcion: 'SANTA ELENA', departamento: 4 },
  { codigo: 41, descripcion: 'TOBATI', departamento: 4 },
  { codigo: 42, descripcion: 'VALENZUELA', departamento: 4 },
  { codigo: 43, descripcion: 'LOMA GRANDE', departamento: 4 },
  { codigo: 44, descripcion: 'SAN JOSE OBRERO', departamento: 4 },
  { codigo: 214, descripcion: 'MBOCAYATY DEL YHAGUY', departamento: 4 },
  { codigo: 45, descripcion: 'VILLARRICA', departamento: 5 },
  { codigo: 46, descripcion: 'SAN SALVADOR', departamento: 5 },
  { codigo: 47, descripcion: 'BORJA', departamento: 5 },
  {
    codigo: 48,
    descripcion: 'INDEPENDENCIA (R.D.MELGAREJO)',
    departamento: 5,
  },
  { codigo: 49, descripcion: 'GRAL.EUGENIO A. GARAY', departamento: 5 },
  { codigo: 50, descripcion: 'CNEL. MARTINEZ', departamento: 5 },
  { codigo: 51, descripcion: 'JOSE FASSARDI', departamento: 5 },
  { codigo: 52, descripcion: 'FELIX PEREZ CARDOZO', departamento: 5 },
  { codigo: 53, descripcion: 'MAURICIO JOSE TROCHE', departamento: 5 },
  { codigo: 54, descripcion: 'ITAPE', departamento: 5 },
  { codigo: 55, descripcion: 'ITURBE', departamento: 5 },
  { codigo: 56, descripcion: 'MBOCAYATY', departamento: 5 },
  { codigo: 57, descripcion: 'NATALICIO TALAVERA', departamento: 5 },
  { codigo: 58, descripcion: 'ÑUMI', departamento: 5 },
  { codigo: 59, descripcion: 'YATAITY', departamento: 5 },
  { codigo: 60, descripcion: 'DR. BOTREL', departamento: 5 },
  { codigo: 225, descripcion: 'PASO YOBAY', departamento: 5 },
  { codigo: 246, descripcion: 'SIN EQUIVALENCIA', departamento: 5 },
  { codigo: 265, descripcion: 'TEBICUARY', departamento: 5 },
  { codigo: 61, descripcion: 'CNEL. OVIEDO', departamento: 6 },
  { codigo: 62, descripcion: 'CAAGUAZU', departamento: 6 },
  { codigo: 63, descripcion: 'CARAYAO', departamento: 6 },
  { codigo: 64, descripcion: 'CECILIO BAEZ', departamento: 6 },
  { codigo: 65, descripcion: 'NUEVA LONDRES', departamento: 6 },
  { codigo: 66, descripcion: 'SAN JOAQUIN', departamento: 6 },
  { codigo: 67, descripcion: 'SAN JOSE DE LOS ARROYOS', departamento: 6 },
  { codigo: 68, descripcion: 'YHU', departamento: 6 },
  { codigo: 69, descripcion: 'JUAN MANUEL FRUTOS', departamento: 6 },
  { codigo: 70, descripcion: 'REPATRIACION', departamento: 6 },
  { codigo: 71, descripcion: 'SANTA ROSA DEL MBUTUY', departamento: 6 },
  { codigo: 72, descripcion: 'J. EULOGIO ESTIGARRIBIA', departamento: 6 },
  { codigo: 73, descripcion: 'JOSE D. OCAMPOS', departamento: 6 },
  { codigo: 74, descripcion: 'R.I.3 CORRALES', departamento: 6 },
  { codigo: 75, descripcion: 'RAUL A. OVIEDO', departamento: 6 },
  { codigo: 76, descripcion: 'MCAL.F.SOLANO LOPEZ', departamento: 6 },
  { codigo: 227, descripcion: '3 DE FEBRERO', departamento: 6 },
  { codigo: 228, descripcion: 'SIMON BOLIVAR', departamento: 6 },
  { codigo: 229, descripcion: 'LA PASTORA', departamento: 6 },
  { codigo: 237, descripcion: 'VAQUERIA', departamento: 6 },
  { codigo: 244, descripcion: 'ESCULIES', departamento: 6 },
  { codigo: 275, descripcion: 'TEMBIAPORA', departamento: 6 },
  { codigo: 276, descripcion: 'NUEVA TOLEDO', departamento: 6 },
  { codigo: 77, descripcion: 'CAAZAPA', departamento: 7 },
  { codigo: 78, descripcion: 'BUENA VISTA', departamento: 7 },
  { codigo: 79, descripcion: 'GRAL. H. MORINIGO', departamento: 7 },
  { codigo: 80, descripcion: 'MACIEL', departamento: 7 },
  { codigo: 81, descripcion: 'MOISES BERTONI', departamento: 7 },
  { codigo: 82, descripcion: 'SAN JUAN NEPOMUCENO', departamento: 7 },
  { codigo: 83, descripcion: 'ABAI', departamento: 7 },
  { codigo: 84, descripcion: 'TAVAI', departamento: 7 },
  { codigo: 85, descripcion: 'YEGROS', departamento: 7 },
  { codigo: 86, descripcion: 'YUTY', departamento: 7 },
  { codigo: 272, descripcion: '3 DE MAYO', departamento: 7 },
  { codigo: 87, descripcion: 'ENCARNACION', departamento: 8 },
  { codigo: 88, descripcion: 'BELLA VISTA', departamento: 8 },
  { codigo: 89, descripcion: 'CAMBYRETA', departamento: 8 },
  { codigo: 90, descripcion: 'CAPITAN MEZA', departamento: 8 },
  { codigo: 91, descripcion: 'CARMEN DEL PARANA', departamento: 8 },
  { codigo: 92, descripcion: 'CAPITAN MIRANDA', departamento: 8 },
  { codigo: 93, descripcion: 'CORONEL BOGADO', departamento: 8 },
  { codigo: 94, descripcion: 'FRAM', departamento: 8 },
  { codigo: 95, descripcion: 'GRAL. ARTIGAS', departamento: 8 },
  { codigo: 96, descripcion: 'GRAL. DELGADO', departamento: 8 },
  { codigo: 97, descripcion: 'HOHENAU', departamento: 8 },
  { codigo: 98, descripcion: 'JESUS', departamento: 8 },
  { codigo: 99, descripcion: 'OBLIGADO', departamento: 8 },
  { codigo: 100, descripcion: 'SAN COSME Y DAMIAN', departamento: 8 },
  { codigo: 101, descripcion: 'SAN PEDRO DEL PARANA', departamento: 8 },
  { codigo: 102, descripcion: 'NUEVA ALBORADA', departamento: 8 },
  { codigo: 103, descripcion: 'TRINIDAD', departamento: 8 },
  { codigo: 104, descripcion: 'NATALIO', departamento: 8 },
  { codigo: 105, descripcion: 'JOSE LEANDRO OVIEDO', departamento: 8 },
  { codigo: 106, descripcion: 'SAN RAFAEL DEL PARANA', departamento: 8 },
  { codigo: 107, descripcion: 'CARLOS A. LOPEZ', departamento: 8 },
  { codigo: 108, descripcion: 'JULIO D. OTAÑO', departamento: 8 },
  { codigo: 109, descripcion: 'EDELIRA', departamento: 8 },
  { codigo: 110, descripcion: 'SAN JUAN DEL PARANA', departamento: 8 },
  { codigo: 111, descripcion: 'LA PAZ', departamento: 8 },
  { codigo: 112, descripcion: 'TOMAS R. PEREIRA', departamento: 8 },
  { codigo: 113, descripcion: 'YATYTAY', departamento: 8 },
  { codigo: 114, descripcion: 'HERIBERTA S.DE IGLESIAS', departamento: 8 },
  { codigo: 221, descripcion: 'PIRAPO', departamento: 8 },
  { codigo: 232, descripcion: 'ITAPUA POTY', departamento: 8 },
  { codigo: 243, descripcion: 'FEDERICO CHAVEZ', departamento: 8 },
  { codigo: 262, descripcion: 'ALTO VERA', departamento: 8 },
  { codigo: 115, descripcion: 'SAN JUAN BAUTISTA', departamento: 9 },
  { codigo: 116, descripcion: 'AYOLAS', departamento: 9 },
  { codigo: 117, descripcion: 'SAN IGNACIO', departamento: 9 },
  { codigo: 118, descripcion: 'SAN MIGUEL', departamento: 9 },
  { codigo: 119, descripcion: 'SAN PATRICIO', departamento: 9 },
  { codigo: 120, descripcion: 'SANTIAGO', departamento: 9 },
  { codigo: 121, descripcion: 'SANTA MARIA', departamento: 9 },
  { codigo: 122, descripcion: 'SANTA ROSA', departamento: 9 },
  { codigo: 123, descripcion: 'VILLA FLORIDA', departamento: 9 },
  { codigo: 124, descripcion: 'YABEBYRY', departamento: 9 },
  { codigo: 125, descripcion: 'PARAGUARI', departamento: 10 },
  { codigo: 126, descripcion: 'ACAHAY', departamento: 10 },
  { codigo: 127, descripcion: 'CAAPUCU', departamento: 10 },
  { codigo: 128, descripcion: 'CABALLERO', departamento: 10 },
  { codigo: 129, descripcion: 'CARAPEGUA', departamento: 10 },
  { codigo: 130, descripcion: 'LA COLMENA', departamento: 10 },
  { codigo: 131, descripcion: 'ESCOBAR', departamento: 10 },
  { codigo: 132, descripcion: 'MBUYAPEY', departamento: 10 },
  { codigo: 133, descripcion: 'PIRAYU', departamento: 10 },
  { codigo: 134, descripcion: 'QUIINDY', departamento: 10 },
  { codigo: 135, descripcion: 'ROQUE GONZALEZ', departamento: 10 },
  { codigo: 136, descripcion: 'SAPUCAI', departamento: 10 },
  { codigo: 137, descripcion: 'YBYCUI', departamento: 10 },
  { codigo: 138, descripcion: 'QUYQUYHO', departamento: 10 },
  { codigo: 139, descripcion: 'YBYTYMI', departamento: 10 },
  { codigo: 140, descripcion: 'TEBICUARY MI', departamento: 10 },
  { codigo: 141, descripcion: 'YAGUARON', departamento: 10 },
  { codigo: 142, descripcion: 'HERNANDARIAS', departamento: 11 },
  { codigo: 143, descripcion: 'DOMINGO MARTINEZ DE IRALA', departamento: 11 },
  { codigo: 144, descripcion: 'ÑACUNDAY', departamento: 11 },
  { codigo: 145, descripcion: 'CIUDAD DEL ESTE', departamento: 11 },
  { codigo: 146, descripcion: 'JUAN LEON MALLORQUIN', departamento: 11 },
  { codigo: 147, descripcion: 'ITAKYRY', departamento: 11 },
  { codigo: 148, descripcion: "JUAN E.O'LEARY", departamento: 11 },
  { codigo: 149, descripcion: 'PRESIDENTE FRANCO', departamento: 11 },
  { codigo: 150, descripcion: 'YGUAZU', departamento: 11 },
  { codigo: 151, descripcion: 'SAN CRISTOBAL', departamento: 11 },
  { codigo: 209, descripcion: 'SANTA RITA', departamento: 11 },
  { codigo: 210, descripcion: 'MINGA GUAZU', departamento: 11 },
  { codigo: 211, descripcion: 'LOS CEDRALES', departamento: 11 },
  { codigo: 212, descripcion: 'SAN ALBERTO', departamento: 11 },
  { codigo: 213, descripcion: 'MINGA PORA', departamento: 11 },
  { codigo: 215, descripcion: 'NARANJAL', departamento: 11 },
  { codigo: 216, descripcion: 'SANTA ROSA DEL MONDAY', departamento: 11 },
  { codigo: 217, descripcion: 'IRUÑA', departamento: 11 },
  { codigo: 219, descripcion: 'MBARACAYU', departamento: 11 },
  { codigo: 239, descripcion: 'SANTA FE DEL PARANA', departamento: 11 },
  { codigo: 240, descripcion: 'NUEVA ESPERANZA', departamento: 11 },
  { codigo: 269, descripcion: 'TAVAPY', departamento: 11 },
  { codigo: 273, descripcion: 'DR. RAUL PEÑA', departamento: 11 },
  { codigo: 152, descripcion: 'AREGUA', departamento: 12 },
  { codigo: 153, descripcion: 'CAPIATA', departamento: 12 },
  { codigo: 154, descripcion: 'FERNANDO DE LA MORA', departamento: 12 },
  { codigo: 155, descripcion: 'GUARAMBARE', departamento: 12 },
  { codigo: 156, descripcion: 'ITA', departamento: 12 },
  { codigo: 157, descripcion: 'ITAUGUA', departamento: 12 },
  { codigo: 158, descripcion: 'LIMPIO', departamento: 12 },
  { codigo: 159, descripcion: 'LUQUE', departamento: 12 },
  { codigo: 160, descripcion: 'MARIANO ROQUE ALONSO', departamento: 12 },
  { codigo: 161, descripcion: 'ÑEMBY', departamento: 12 },
  { codigo: 162, descripcion: 'NUEVA ITALIA', departamento: 12 },
  { codigo: 163, descripcion: 'SAN ANTONIO', departamento: 12 },
  { codigo: 164, descripcion: 'SAN LORENZO', departamento: 12 },
  { codigo: 165, descripcion: 'VILLA ELISA', departamento: 12 },
  { codigo: 166, descripcion: 'VILLETA', departamento: 12 },
  { codigo: 167, descripcion: 'YPACARAI', departamento: 12 },
  { codigo: 168, descripcion: 'YPANE', departamento: 12 },
  { codigo: 169, descripcion: 'LAMBARE', departamento: 12 },
  { codigo: 170, descripcion: 'J.AUGUSTO SALDIVAR', departamento: 12 },
  { codigo: 277, descripcion: 'LOMA PYTA', departamento: 12 },
  { codigo: 171, descripcion: 'PILAR', departamento: 13 },
  { codigo: 172, descripcion: 'ALBERDI', departamento: 13 },
  { codigo: 173, descripcion: 'CERRITO', departamento: 13 },
  { codigo: 174, descripcion: 'DESMOCHADOS', departamento: 13 },
  { codigo: 175, descripcion: 'GUAZU CUA', departamento: 13 },
  { codigo: 176, descripcion: 'HUMAITA', departamento: 13 },
  { codigo: 177, descripcion: 'ISLA UMBU', departamento: 13 },
  { codigo: 178, descripcion: 'LAURELES', departamento: 13 },
  { codigo: 179, descripcion: 'PASO DE PATRIA', departamento: 13 },
  { codigo: 180, descripcion: 'MAYOR J.D.MARTINEZ', departamento: 13 },
  { codigo: 181, descripcion: 'SAN JUAN DE ÑEEMBUCU', departamento: 13 },
  { codigo: 182, descripcion: 'TACUARAS', departamento: 13 },
  { codigo: 183, descripcion: 'VILLA OLIVA', departamento: 13 },
  { codigo: 184, descripcion: 'VILLALBIN', departamento: 13 },
  { codigo: 203, descripcion: 'GRAL.JOSE EDUVIGIS DIAZ', departamento: 13 },
  { codigo: 205, descripcion: 'VILLA FRANCA', departamento: 13 },
  { codigo: 230, descripcion: 'VILLA FRANCA', departamento: 13 },
  { codigo: 231, descripcion: 'VILLALBIN', departamento: 13 },
  { codigo: 185, descripcion: 'PEDRO JUAN CABALLERO', departamento: 14 },
  { codigo: 186, descripcion: 'BELLA VISTA', departamento: 14 },
  { codigo: 187, descripcion: 'CAPITAN BADO', departamento: 14 },
  { codigo: 278, descripcion: 'KARAPAI', departamento: 14 },
  { codigo: 279, descripcion: 'ZANJA PYTA', departamento: 14 },
  { codigo: 188, descripcion: 'VILLA HAYES', departamento: 15 },
  {
    codigo: 189,
    descripcion: 'BENJAMIN ACEVAL(MONTE SOCIEDAD',
    departamento: 15,
  },
  { codigo: 190, descripcion: 'PTO.PINAZCO', departamento: 15 },
  { codigo: 191, descripcion: 'NANAWA', departamento: 15 },
  { codigo: 206, descripcion: 'POZO COLORADO', departamento: 15 },
  { codigo: 242, descripcion: 'JOSE FALCON', departamento: 15 },
  { codigo: 261, descripcion: 'TTE. 1RO. IRALA FERNANDEZ', departamento: 15 },
  { codigo: 264, descripcion: 'TENIENTE ESTEBAN MARTINEZ', departamento: 15 },
  { codigo: 192, descripcion: 'MCAL.ESTIGARRIBIA', departamento: 16 },
  { codigo: 193, descripcion: 'BOQUERON', departamento: 16 },
  { codigo: 194, descripcion: 'PEDRO P.PEÑA', departamento: 16 },
  { codigo: 234, descripcion: 'GRAL. EUGENIO A. GARAY', departamento: 16 },
  { codigo: 259, descripcion: 'FILADELFIA', departamento: 16 },
  { codigo: 260, descripcion: 'LOMA PLATA', departamento: 16 },
  { codigo: 195, descripcion: 'FUERTE OLIMPO', departamento: 17 },
  { codigo: 196, descripcion: 'BAHIA NEGRA', departamento: 17 },
  { codigo: 218, descripcion: 'PUERTO CASADO', departamento: 17 },
  { codigo: 223, descripcion: 'PUERTO GUARANI', departamento: 17 },
  { codigo: 233, descripcion: 'MAYOR PABLO LAGERENZA', departamento: 17 },
  { codigo: 266, descripcion: 'CARMELO PERALTA', departamento: 17 },
  { codigo: 197, descripcion: 'SAN ISIDRO DEL CURUGUATY', departamento: 18 },
  { codigo: 198, descripcion: 'VILLA YGATIMI', departamento: 18 },
  { codigo: 199, descripcion: 'YPEJHU', departamento: 18 },
  { codigo: 200, descripcion: 'CORPUS CHRISTI', departamento: 18 },
  { codigo: 201, descripcion: 'ITANARA', departamento: 18 },
  {
    codigo: 202,
    descripcion: 'FRANCISCO CABALLERO ALVAREZ',
    departamento: 18,
  },
  { codigo: 207, descripcion: 'SALTO DEL GUAIRA', departamento: 18 },
  { codigo: 235, descripcion: 'LA PALOMA', departamento: 18 },
  { codigo: 236, descripcion: 'KATUETE', departamento: 18 },
  { codigo: 238, descripcion: 'NUEVA ESPERANZA', departamento: 18 },
  { codigo: 241, descripcion: 'YASY KAÑY', departamento: 18 },
  { codigo: 271, descripcion: 'YBYRAROBANA', departamento: 18 },
  { codigo: 274, descripcion: 'YBY PYTA', departamento: 18 },
  { codigo: 283, descripcion: 'MARACANA', departamento: 18 },
  { codigo: 284, descripcion: 'PUERTO ADELA', departamento: 18 },
]
